export const demoRooms = [
  {
    name: "Patna Podcast Hub",
    slug: "patna-podcast-hub-boring-road",
    description: "Professional podcast recording studio in the heart of Patna. Features 4-person seating, broadcast-quality microphones, acoustic foam panels, and real-time monitoring. Perfect for podcasters, interviewers, and content creators looking for a premium recording environment.",
    category: "podcast",
    city: "Patna",
    address: "Boring Road, Near Patna Central Mall",
    images: [
      "/rooms/podcast-wide.jpg",
      "/rooms/podcast-wide-2.jpg",
      "/rooms/podcast-360.jpg",
      "/rooms/podcast-exterior.jpg",
      "/rooms/podcast-equipment.jpg",
      "/rooms/podcast-lounge.jpg",
      "/rooms/podcast-corner.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Microphone", "Speakers", "Audio Interface", "LED Lights", "Monitoring Headphones", "Pop Filter"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: true,
    rating: 4.8,
    reviews: 24,
    capacity: 4,
    mapLink: "https://maps.google.com/?q=Boring+Road+Patna",
  },
  {
    name: "CreatorStudioX YouTube Setup",
    slug: "creatorstudiox-youtube-kankarbagh",
    description: "Fully equipped YouTube filming studio with green screen, professional lighting, camera on tripod, and dual monitor editing desk. Ideal for YouTubers, tutorial creators, and video content makers.",
    category: "youtube",
    city: "Patna",
    address: "Kankarbagh Main Road, Near P&M Mall",
    images: [
      "/rooms/youtube-wide.jpg",
      "/rooms/youtube-wide-2.jpg",
      "/rooms/youtube-exterior.jpg",
      "/rooms/editing-suite.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Monitor", "Green Screen", "Teleprompter", "Ring Light"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: true,
    rating: 4.7,
    reviews: 18,
    capacity: 3,
    mapLink: "https://maps.google.com/?q=Kankarbagh+Patna",
  },
  {
    name: "Patna Sound Lab",
    slug: "patna-sound-lab-fraser-road",
    description: "Professional music recording studio with mixing console, vocal booth, studio monitors, and MIDI keyboard. Perfect for musicians, singers, and audio producers.",
    category: "music",
    city: "Patna",
    address: "Fraser Road, Near Maurya Lok",
    images: [
      "/rooms/music-wide.jpg",
      "/rooms/music-wide-2.jpg",
      "/rooms/music-360.jpg",
      "/rooms/music-lounge.jpg",
      "/rooms/music-vocal.jpg",
      "/rooms/podcast-equipment.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Microphone", "Speakers", "Audio Interface", "MIDI Keyboard", "Studio Monitors", "Vocal Booth"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: true,
    rating: 4.9,
    reviews: 32,
    capacity: 5,
    mapLink: "https://maps.google.com/?q=Fraser+Road+Patna",
  },
  {
    name: "SnapStudio Photo Lab",
    slug: "snapstudio-photo-gardanibagh",
    description: "Premium photography studio with seamless backdrop, professional strobe lights, reflectors, and wide shooting space. Ideal for product photography, portraits, and fashion shoots.",
    category: "photography",
    city: "Patna",
    address: "Gardanibagh, Near Patna Museum",
    images: [
      "/rooms/photo-wide.jpg",
      "/rooms/photo-wide-2.jpg",
      "/rooms/photo-360.jpg",
      "/rooms/photo-mirror.jpg",
      "/rooms/youtube-wide.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Backdrop", "Reflectors", "Strobe Lights", "Softbox"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.6,
    reviews: 15,
    capacity: 6,
    mapLink: "https://maps.google.com/?q=Gardanibagh+Patna",
  },
  {
    name: "DanceFloor Patna",
    slug: "dancefloor-patna-rajendranagar",
    description: "Spacious dance and choreography rehearsal studio with full-wall mirrors, wooden sprung floor, and premium sound system. Perfect for dance practice, choreography sessions, and fitness content.",
    category: "dance",
    city: "Patna",
    address: "Rajendra Nagar, Near Patna Airport Road",
    images: [
      "/rooms/dance-wide.jpg",
      "/rooms/dance-wide-2.jpg",
      "/rooms/gaming-lounge.jpg",
      "/rooms/podcast-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Speakers", "LED Lights", "Mirrors", "Ballet Barres", "Sprung Floor"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.5,
    reviews: 12,
    capacity: 8,
    mapLink: "https://maps.google.com/?q=Rajendra+Nagar+Patna",
  },
  {
    name: "Patna Creators Hub",
    slug: "patna-creators-hub-dakbungalow",
    description: "Modern co-working space with glass conference room, ergonomic chairs, large display screens, and collaborative workspace. Perfect for meetings, team collaboration, and startup work.",
    category: "coworking",
    city: "Patna",
    address: "Dak Bungalow Road, Near Patna Junction",
    images: [
      "/rooms/coworking-wide.jpg",
      "/rooms/coworking-wide-2.jpg",
      "/rooms/meeting-wide.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/podcast-lounge.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Monitor", "LED Lights", "Speakers", "Whiteboard", "Projector"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.4,
    reviews: 9,
    capacity: 10,
    mapLink: "https://maps.google.com/?q=Dak+Bungalow+Patna",
  },
  {
    name: "GameZone Pro Streaming",
    slug: "gamezone-pro-streaming-bailey-road",
    description: "Gaming and esports streaming room with RGB setup, multiple monitors, professional streaming camera, and soundproofing. Perfect for gamers, streamers, and esports content creators.",
    category: "gaming",
    city: "Patna",
    address: "Bailey Road, Near Big Bazaar",
    images: [
      "/rooms/gaming-wide.jpg",
      "/rooms/gaming-wide-2.jpg",
      "/rooms/gaming-360.jpg",
      "/rooms/gaming-rgb.jpg",
      "/rooms/gaming-lounge.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Monitor", "Speakers", "Gaming Chair", "RGB Setup"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.7,
    reviews: 21,
    capacity: 2,
    mapLink: "https://maps.google.com/?q=Bailey+Road+Patna",
  },
  {
    name: "LiveStream Studio Patna",
    slug: "livestream-studio-patliputra",
    description: "Multi-camera live streaming studio with professional lighting rig, teleprompter, and premium streaming equipment. Ideal for live events, webinars, and professional streaming.",
    category: "streaming",
    city: "Patna",
    address: "Patliputra Colony, Near Patliputra Sports Complex",
    images: [
      "/rooms/streaming-wide.jpg",
      "/rooms/streaming-wide-2.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/gaming-wide.jpg",
      "/rooms/editing-suite.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "Microphone", "LED Lights", "Monitor", "Teleprompter", "Multi-Cam Setup"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: true,
    rating: 4.8,
    reviews: 14,
    capacity: 4,
    mapLink: "https://maps.google.com/?q=Patliputra+Patna",
  },
  {
    name: "CreatorSpace Kankarbagh",
    slug: "creatorspace-kankarbagh-main",
    description: "Spacious dual-setup creator studio with separate filming and editing zones. Features RGB ambient lighting, green screen wall, dual monitor setup, and high-speed WiFi. Perfect for tech reviewers, gaming streamers, and multi-format content creators.",
    category: "youtube",
    city: "Patna",
    address: "Kankarbagh Main Road, Near More Supermarket",
    images: [
      "/rooms/youtube-wide.jpg",
      "/rooms/gaming-wide.jpg",
      "/rooms/editing-suite.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/youtube-wide-2.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Monitor", "Green Screen", "RGB Lighting", "Dual Setup"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.6,
    reviews: 11,
    capacity: 3,
    mapLink: "https://maps.google.com/?q=Kankarbagh+Patna",
  },
  {
    name: "Patna Rehearsal Central",
    slug: "patna-rehearsal-central-anandpuri",
    description: "Large rehearsal and performance space with professional acoustics, stage lighting, mirror wall, and premium PA system. Ideal for band practice, dance rehearsals, theatre practice, and audition recordings. The space is soundproofed for uninterrupted sessions.",
    category: "music",
    city: "Patna",
    address: "Anandpuri, Near NIT Patna Gate",
    images: [
      "/rooms/music-wide.jpg",
      "/rooms/dance-wide.jpg",
      "/rooms/music-wide-2.jpg",
      "/rooms/music-vocal.jpg",
      "/rooms/podcast-lounge.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Microphone", "Speakers", "Audio Interface", "MIDI Keyboard", "Stage Lights", "PA System", "Mirror Wall"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: true,
    rating: 4.9,
    reviews: 19,
    capacity: 12,
    mapLink: "https://maps.google.com/?q=Anandpuri+Patna",
  },
  {
    name: "Mini Studio Express",
    slug: "mini-studio-express-bailey-road",
    description: "Compact and affordable single-person studio perfect for quick recordings, voiceovers, podcast episodes, and selfie-style videos. Features ring light, smartphone mount, mic, and acoustic treatment. Best for creators on a budget who need a professional setup without breaking the bank.",
    category: "podcast",
    city: "Patna",
    address: "Bailey Road, Near Patna Zoo",
    images: [
      "/rooms/podcast-wide.jpg",
      "/rooms/youtube-wide.jpg",
      "/rooms/podcast-corner.jpg",
      "/rooms/podcast-wide-2.jpg",
      "/rooms/equipment-corner.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Microphone", "Ring Light", "Smartphone Mount", "Pop Filter", "LED Lights"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.3,
    reviews: 8,
    capacity: 1,
    mapLink: "https://maps.google.com/?q=Bailey+Road+Patna",
  },
  {
    name: "Corporate Meet Hub",
    slug: "corporate-meet-hub-saguna-more",
    description: "Premium meeting and conference room with 4K display, video conferencing setup, whiteboard, and ergonomic seating for 8 people. Perfect for team meetings, client presentations, training sessions, and webinar hosting. Located in a quiet commercial complex with ample parking.",
    category: "meeting",
    city: "Patna",
    address: "Saguna More, Near Axis Bank Building",
    images: [
      "/rooms/meeting-wide.jpg",
      "/rooms/coworking-wide.jpg",
      "/rooms/coworking-wide-2.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/youtube-wide-2.jpg",
      "/rooms/lounge-area.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Monitor", "Projector", "Whiteboard", "Video Conferencing", "Speakers", "Ergonomic Chairs"],
    pricePerHour: 5,
    pricePerDay: 5,
    featured: false,
    rating: 4.5,
    reviews: 7,
    capacity: 8,
    mapLink: "https://maps.google.com/?q=Saguna+More+Patna",
  },
];
