import { NextResponse } from "next/server";
import connectDB from "@/lib/db";
import Room from "@/models/Room";

const demoRooms = [
  {
    name: "Patna Podcast Hub",
    slug: "patna-podcast-hub-boring-road",
    description: "Professional podcast recording studio in the heart of Patna. Features 4-person seating, broadcast-quality microphones, acoustic foam panels, and real-time monitoring. Perfect for podcasters, interviewers, and content creators looking for a premium recording environment.",
    category: "podcast",
    city: "Patna",
    address: "Boring Road, Near Patna Central Mall",
    images: [
      "/rooms/podcast-wide.jpg",
      "/rooms/podcast-exterior.jpg",
      "/rooms/podcast-equipment.jpg",
      "/rooms/podcast-lounge.jpg",
      "/rooms/podcast-corner.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Microphone", "Speakers", "Audio Interface", "LED Lights"],
    pricePerHour: 499,
    pricePerDay: 3499,
    featured: true,
    rating: 4.8,
    reviews: 24,
    capacity: 4,
    mapLink: "https://maps.google.com/?q=Boring+Road+Patna",
  },
  {
    name: "CreatorStudioX YouTube Setup",
    slug: "creatorstudiox-youtube-kankarbagh",
    description: "Fully equipped YouTube filming studio with green screen, professional lighting, camera on tripod, and dual monitor editing desk. Ideal for YouTubers, tutorial creators, and video content makers.",
    category: "youtube",
    city: "Patna",
    address: "Kankarbagh Main Road, Near P&M Mall",
    images: [
      "/rooms/youtube-wide.jpg",
      "/rooms/youtube-exterior.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Monitor", "Green Screen"],
    pricePerHour: 599,
    pricePerDay: 3999,
    featured: true,
    rating: 4.7,
    reviews: 18,
    capacity: 3,
    mapLink: "https://maps.google.com/?q=Kankarbagh+Patna",
  },
  {
    name: "Patna Sound Lab",
    slug: "patna-sound-lab-fraser-road",
    description: "Professional music recording studio with mixing console, vocal booth, studio monitors, and MIDI keyboard. Perfect for musicians, singers, and audio producers.",
    category: "music",
    city: "Patna",
    address: "Fraser Road, Near Maurya Lok",
    images: [
      "/rooms/music-wide.jpg",
      "/rooms/music-lounge.jpg",
      "/rooms/music-vocal.jpg",
      "/rooms/podcast-equipment.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Microphone", "Speakers", "Audio Interface", "MIDI Keyboard"],
    pricePerHour: 699,
    pricePerDay: 4499,
    featured: true,
    rating: 4.9,
    reviews: 32,
    capacity: 5,
    mapLink: "https://maps.google.com/?q=Fraser+Road+Patna",
  },
  {
    name: "SnapStudio Photo Lab",
    slug: "snapstudio-photo-gardanibagh",
    description: "Premium photography studio with seamless backdrop, professional strobe lights, reflectors, and wide shooting space. Ideal for product photography, portraits, and fashion shoots.",
    category: "photography",
    city: "Patna",
    address: "Gardanibagh, Near Patna Museum",
    images: [
      "/rooms/photo-wide.jpg",
      "/rooms/photo-mirror.jpg",
      "/rooms/youtube-wide.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Backdrop", "Reflectors"],
    pricePerHour: 449,
    pricePerDay: 2999,
    featured: false,
    rating: 4.6,
    reviews: 15,
    capacity: 6,
    mapLink: "https://maps.google.com/?q=Gardanibagh+Patna",
  },
  {
    name: "DanceFloor Patna",
    slug: "dancefloor-patna-rajendranagar",
    description: "Spacious dance and choreography rehearsal studio with full-wall mirrors, wooden sprung floor, and premium sound system. Perfect for dance practice, choreography sessions, and fitness content.",
    category: "dance",
    city: "Patna",
    address: "Rajendra Nagar, Near Patna Airport Road",
    images: [
      "/rooms/dance-wide.jpg",
      "/rooms/gaming-lounge.jpg",
      "/rooms/podcast-corner.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Speakers", "LED Lights", "Mirrors"],
    pricePerHour: 399,
    pricePerDay: 2499,
    featured: false,
    rating: 4.5,
    reviews: 12,
    capacity: 8,
    mapLink: "https://maps.google.com/?q=Rajendra+Nagar+Patna",
  },
  {
    name: "Patna Creators Hub",
    slug: "patna-creators-hub-dakbungalow",
    description: "Modern co-working space with glass conference room, ergonomic chairs, large display screens, and collaborative workspace. Perfect for meetings, team collaboration, and startup work.",
    category: "coworking",
    city: "Patna",
    address: "Dak Bungalow Road, Near Patna Junction",
    images: [
      "/rooms/coworking-wide.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/podcast-lounge.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Monitor", "LED Lights", "Speakers"],
    pricePerHour: 349,
    pricePerDay: 1999,
    featured: false,
    rating: 4.4,
    reviews: 9,
    capacity: 10,
    mapLink: "https://maps.google.com/?q=Dak+Bungalow+Patna",
  },
  {
    name: "GameZone Pro Streaming",
    slug: "gamezone-pro-streaming-bailey-road",
    description: "Gaming and esports streaming room with RGB setup, multiple monitors, professional streaming camera, and soundproofing. Perfect for gamers, streamers, and esports content creators.",
    category: "gaming",
    city: "Patna",
    address: "Bailey Road, Near Big Bazaar",
    images: [
      "/rooms/gaming-wide.jpg",
      "/rooms/gaming-rgb.jpg",
      "/rooms/gaming-lounge.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "LED Lights", "Monitor", "Speakers"],
    pricePerHour: 549,
    pricePerDay: 3499,
    featured: false,
    rating: 4.7,
    reviews: 21,
    capacity: 2,
    mapLink: "https://maps.google.com/?q=Bailey+Road+Patna",
  },
  {
    name: "LiveStream Studio Patna",
    slug: "livestream-studio-patliputra",
    description: "Multi-camera live streaming studio with professional lighting rig, teleprompter, and premium streaming equipment. Ideal for live events, webinars, and professional streaming.",
    category: "streaming",
    city: "Patna",
    address: "Patliputra Colony, Near Patliputra Sports Complex",
    images: [
      "/rooms/streaming-wide.jpg",
      "/rooms/streaming-desk.jpg",
      "/rooms/gaming-wide.jpg",
      "/rooms/exterior-main.jpg",
    ],
    equipment: ["WiFi", "Camera", "Microphone", "LED Lights", "Monitor"],
    pricePerHour: 649,
    pricePerDay: 4299,
    featured: true,
    rating: 4.8,
    reviews: 14,
    capacity: 4,
    mapLink: "https://maps.google.com/?q=Patliputra+Patna",
  },
];

export async function GET() {
  try {
    await connectDB();

    // Clear existing rooms and insert demo data
    await Room.deleteMany({});
    await Room.insertMany(demoRooms);

    return NextResponse.json({
      success: true,
      message: "Demo rooms seeded successfully",
      count: demoRooms.length,
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json(
      { success: false, message: "Seed failed" },
      { status: 500 }
    );
  }
}
