import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Room from '@/models/Room';

const patnaRooms = [
  {
    name: 'Neon Glow Creator Studio',
    description: 'A vibrant neon-lit creator studio perfect for Instagram reels, TikTok videos, and aesthetic content creation. Features RGB lighting, neon walls, and professional ring light setup.',
    category: 'Neon RGB Creator Room',
    pricePerHour: 299,
    city: 'Patna',
    area: 'Boring Road',
    address: '3rd Floor, Krishna Complex, Boring Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=600&fit=crop',
    ],
    equipment: ['RGB LED Panels', 'Neon Wall', 'Ring Light', 'Tripod', 'Bluetooth Speaker', 'AC', 'WiFi'],
    features: ['Soundproof', 'Neon Ambient Lighting', 'Props Available', 'Makeup Corner'],
    maxPeople: 3,
    rating: 4.8,
    reviewCount: 24,
  },
  {
    name: 'Pro Podcast Hub Patna',
    description: 'Professional podcast studio with acoustic treatment, multi-mic setup, and soundproof environment. Perfect for podcasters, interviewers, and voice-over artists.',
    category: 'Podcast Studio',
    pricePerHour: 399,
    city: 'Patna',
    area: 'Kankarbagh',
    address: '1st Floor, AIM Building, Kankarbagh Main Road, Patna, Bihar 800020',
    images: [
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=800&h=600&fit=crop',
    ],
    equipment: ['Shure SM7B Mic', 'Acoustic Panels', 'Pop Filter', 'Mixer', 'Headphones', 'AC', 'WiFi'],
    features: ['Soundproof', 'Echo-Free', 'Live Monitoring', 'Noise Cancellation'],
    maxPeople: 4,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    name: 'Gaming Arena X',
    description: 'High-end gaming and streaming studio with RGB gaming PC, dual monitors, stream deck, and professional lighting. Built for gamers and streamers.',
    category: 'Gaming & Streaming Room',
    pricePerHour: 449,
    city: 'Patna',
    area: 'Fraser Road',
    address: '2nd Floor, AVR Tower, Fraser Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop',
    ],
    equipment: ['Gaming PC (RTX 4070)', 'Dual 4K Monitors', 'Stream Deck', 'Gaming Chair', 'RGB Keyboard', 'Headset', 'AC', 'WiFi'],
    features: ['144Hz Monitor', 'Streaming Ready', 'Discord Setup', 'Green Screen Option'],
    maxPeople: 2,
    rating: 4.7,
    reviewCount: 18,
  },
  {
    name: 'YouTube Creator Studio',
    description: 'Full-featured YouTube studio with professional camera setup, softbox lighting, teleprompter, and editing station. Perfect for YouTubers and content creators.',
    category: 'YouTube Creator Studio',
    pricePerHour: 499,
    city: 'Patna',
    area: 'Rajendra Nagar',
    address: 'Ground Floor, Mithila Towers, Rajendra Nagar, Patna, Bihar 800016',
    images: [
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1521320226546-87b106956014?w=800&h=600&fit=crop',
    ],
    equipment: ['Sony A7 IV Camera', 'Softbox Lights', 'Teleprompter', 'Lapel Mic', 'Editing Mac', 'Tripod', 'AC', 'WiFi'],
    features: ['4K Recording', 'Chroma Key', 'Script Writing Desk', 'Quick Export'],
    maxPeople: 5,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    name: 'Aesthetic Vibes Studio',
    description: 'Luxury aesthetic room with minimalist design, natural lighting, boho decor, and mirror setups. Perfect for lifestyle creators and beauty influencers.',
    category: 'Luxury Aesthetic Room',
    pricePerHour: 349,
    city: 'Patna',
    area: 'Sri Krishna Puri',
    address: 'Roof Top, Pearl Plaza, Sri Krishna Puri, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&h=600&fit=crop',
    ],
    equipment: ['Ring Light', 'Vanity Mirror', 'Backdrop Stand', 'Decor Props', 'Speaker', 'AC', 'WiFi'],
    features: ['Natural Light', 'Boho Decor', 'Makeup Station', 'Change Room'],
    maxPeople: 4,
    rating: 4.6,
    reviewCount: 15,
  },
  {
    name: 'Product Shoot Pro',
    description: 'Professional product photography studio with white cyclorama, macro lens setup, and controlled lighting. Ideal for e-commerce sellers and product reviewers.',
    category: 'Product Shoot Room',
    pricePerHour: 379,
    city: 'Patna',
    area: 'Patliputra Colony',
    address: '4th Floor, Capital Tower, Patliputra Colony, Patna, Bihar 800013',
    images: [
      'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=800&h=600&fit=crop',
    ],
    equipment: ['DSLR Camera', 'White Cyclorama', 'Softbox Kit', 'Reflector', 'Light Tent', 'Tripod', 'AC', 'WiFi'],
    features: ['360 Setup', 'Macro Mode', 'Color Correction', 'Instant Preview'],
    maxPeople: 3,
    rating: 4.8,
    reviewCount: 22,
  },
  {
    name: 'Reel Factory',
    description: 'Instagram Reel dedicated studio with trending backdrops, quick change setups, and phone-friendly mounting systems. Built for reel creators and short-form content.',
    category: 'Instagram Reel Room',
    pricePerHour: 249,
    city: 'Patna',
    area: 'Bailey Road',
    address: '1st Floor, JD Heights, Bailey Road, Patna, Bihar 800014',
    images: [
      'https://images.unsplash.com/photo-1560964645-6c9ecc759669?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&h=600&fit=crop',
    ],
    equipment: ['Phone Mount', 'Ring Light', 'Trending Backdrops', 'Selfie Stick', 'Gimbal', 'Speaker', 'AC', 'WiFi'],
    features: ['Quick Setup', 'Trending Themes', 'Phone Optimized', 'Collaboration Friendly'],
    maxPeople: 3,
    rating: 4.5,
    reviewCount: 28,
  },
  {
    name: 'Green Screen Studio',
    description: 'Professional green screen studio with chroma key wall, professional camera, and real-time compositing preview. Perfect for VFX creators and virtual backgrounds.',
    category: 'Green Screen Studio',
    pricePerHour: 429,
    city: 'Patna',
    area: 'Gandhi Maidan',
    address: '2nd Floor, Metro Plaza, Gandhi Maidan, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=600&fit=crop',
    ],
    equipment: ['Green Screen Wall', 'Sony Camera', 'LED Panels', 'Foot Pedestal', 'Monitor', 'AC', 'WiFi'],
    features: ['Real-time Preview', 'Wide Angle', 'Floor Green Screen', 'Lighting Grid'],
    maxPeople: 6,
    rating: 4.7,
    reviewCount: 19,
  },
  {
    name: 'Music Recording Lab',
    description: 'Acoustic music recording studio with professional condenser mics, mixing console, and isolated vocal booth. For singers, musicians, and voice artists.',
    category: 'Music Recording Room',
    pricePerHour: 549,
    city: 'Patna',
    area: 'Ashok Rajpath',
    address: 'Basement, Maurya Center, Ashok Rajpath, Patna, Bihar 800006',
    images: [
      'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
    ],
    equipment: ['Condenser Mic', 'Vocal Booth', 'Mixer Console', 'Studio Monitors', 'Keyboard', 'Pop Filter', 'AC', 'WiFi'],
    features: ['Sound Isolation', 'Vocal Booth', 'Multi-track', 'Live Mixing'],
    maxPeople: 4,
    rating: 4.9,
    reviewCount: 12,
  },
  {
    name: 'Live Stream Central',
    description: 'Dedicated live streaming studio with multi-camera setup, professional lighting, and streaming PC with OBS configured. Ready to go live anytime.',
    category: 'Live Streaming Studio',
    pricePerHour: 479,
    city: 'Patna',
    area: 'Dak Bungalow',
    address: '3rd Floor, Unity Tower, Dak Bungalow Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1529511582893-2d7e684dd128?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586953208270-767889db8301?w=800&h=600&fit=crop',
    ],
    equipment: ['Multi-cam Setup', 'Streaming PC', 'LED Panels', 'Professional Mic', 'Monitor Wall', 'AC', 'WiFi'],
    features: ['Multi-platform', 'Real-time Comments', 'Scene Switching', 'Backup Internet'],
    maxPeople: 3,
    rating: 4.8,
    reviewCount: 17,
  },
  {
    name: 'Tech Review Lab',
    description: 'Tech review setup with clean desk, overhead camera, unboxing table, and professional lighting. Perfect for unboxing videos and tech reviews.',
    category: 'Tech Review Setup',
    pricePerHour: 329,
    city: 'Patna',
    area: 'Hajipur Road',
    address: '2nd Floor, Tech Park, Hajipur Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=600&fit=crop',
    ],
    equipment: ['Overhead Camera', 'Unboxing Table', 'Desk Mic', 'Ring Light', 'Phone Stand', 'AC', 'WiFi'],
    features: ['Clean Desk', 'Overhead View', 'Multi-angle', 'Fast Upload'],
    maxPeople: 2,
    rating: 4.6,
    reviewCount: 14,
  },
  {
    name: 'Fashion Shoot Studio',
    description: 'Fashion photography studio with runway setup, multiple backdrop options, strobe lighting, and changing room. Designed for fashion creators and models.',
    category: 'Fashion Shoot Room',
    pricePerHour: 549,
    city: 'Patna',
    area: 'Anandpuri',
    address: 'Ground Floor, Luv Kush Complex, Anandpuri, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
    ],
    equipment: ['Strobe Lights', 'Backdrop System', 'Full Mirror', 'Hair Dryer', 'Steamer', 'AC', 'WiFi'],
    features: ['Runway Space', 'Changing Room', 'Hair Station', 'Multi Backdrops'],
    maxPeople: 6,
    rating: 4.7,
    reviewCount: 20,
  },
  {
    name: 'Couple Creator Suite',
    description: 'Romantic creator studio designed for couple vloggers, relationship content, and duo creators. Warm lighting, cozy setup, and dual camera angles.',
    category: 'Couple Creator Room',
    pricePerHour: 379,
    city: 'Patna',
    area: 'Keshri Nagar',
    address: '1st Floor, Couples Corner, Keshri Nagar, Patna, Bihar 800020',
    images: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&h=600&fit=crop',
    ],
    equipment: ['Dual Camera', 'Warm Lights', 'Couch Setup', 'Selfie Mirror', 'Speaker', 'AC', 'WiFi'],
    features: ['Romantic Ambiance', 'Dual Angle', 'Private Entry', 'Cozy Vibes'],
    maxPeople: 2,
    rating: 4.8,
    reviewCount: 16,
  },
  {
    name: 'Selfie Point X',
    description: 'Instagram-worthy selfie station with multiple themed backdrops, perfect lighting, and props. The go-to spot for selfie lovers and micro-influencers.',
    category: 'Selfie Point Room',
    pricePerHour: 199,
    city: 'Patna',
    area: 'Boring Road',
    address: 'Ground Floor, Selfie World, Boring Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560964645-6b7b7a552625?w=800&h=600&fit=crop',
    ],
    equipment: ['Selfie Ring Light', 'Backdrop Stand', 'Phone Holders', 'Props Box', 'Bluetooth Remote', 'AC', 'WiFi'],
    features: ['Themed Zones', 'Quick Change', 'Instant Share', 'Affordable'],
    maxPeople: 4,
    rating: 4.4,
    reviewCount: 35,
  },
  {
    name: 'AI Creator Workspace',
    description: 'Futuristic AI-powered creator workspace with dual monitors, AI tools pre-installed, voice assistant, and ergonomic setup. For tech creators and AI enthusiasts.',
    category: 'AI Creator Workspace',
    pricePerHour: 419,
    city: 'Patna',
    area: 'SP Verma Road',
    address: '5th Floor, Innovation Hub, SP Verma Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=600&fit=crop',
    ],
    equipment: ['Dual 4K Monitors', 'AI PC Setup', 'Ergonomic Chair', 'Noise-Cancel Headphones', 'Webcam', 'AC', 'WiFi'],
    features: ['AI Tools Ready', 'Voice Assistant', 'Fast Internet', 'Ergonomic'],
    maxPeople: 2,
    rating: 4.6,
    reviewCount: 11,
  },
  {
    name: 'Startup Pitch Room',
    description: 'Professional startup pitch studio with presentation screen, conference table, and investor-ready ambiance. Perfect for startup founders and entrepreneurs.',
    category: 'Startup Pitch Room',
    pricePerHour: 599,
    city: 'Patna',
    area: 'Gandhi Maidan',
    address: '7th Floor, Startup Bhawan, Gandhi Maidan, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
    ],
    equipment: ['Projector', 'Conference Table', 'Whiteboard', 'Mic System', 'Video Camera', 'AC', 'WiFi'],
    features: ['Investor Ready', 'Recording', 'Whiteboard', 'Professional Ambiance'],
    maxPeople: 10,
    rating: 4.9,
    reviewCount: 8,
  },
  {
    name: 'Interview Studio Pro',
    description: 'Professional interview setup with two-camera arrangement, soft lighting, and comfortable seating. Ideal for HR interviews, media interviews, and panel discussions.',
    category: 'Interview Studio',
    pricePerHour: 449,
    city: 'Patna',
    area: 'Frazer Road',
    address: '3rd Floor, Media House, Frazer Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    ],
    equipment: ['Dual Camera', 'Softbox Lights', 'Lapel Mics', 'Monitor', 'Comfortable Chairs', 'AC', 'WiFi'],
    features: ['Two-Camera Setup', 'Noise Free', 'Waiting Area', 'Tea/Coffee'],
    maxPeople: 4,
    rating: 4.7,
    reviewCount: 13,
  },
  {
    name: 'Cinematic Video Lab',
    description: 'High-end cinematic studio with anamorphic lens setup, crane support, and professional cinema lighting. For filmmakers and cinematic content creators.',
    category: 'Cinematic Video Studio',
    pricePerHour: 649,
    city: 'Patna',
    area: 'Lokanayak Ganga Path',
    address: 'Ground Floor, Film City Studio, Lokanayak Ganga Path, Patna, Bihar 800010',
    images: [
      'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=600&fit=crop',
    ],
    equipment: ['Cinema Camera', 'Anamorphic Lens', 'Crane Support', 'Cine Lights', 'Slider', 'AC', 'WiFi'],
    features: ['Wide Space', 'High Ceiling', 'Equipment Support', 'Editing Bay'],
    maxPeople: 8,
    rating: 4.9,
    reviewCount: 7,
  },
  {
    name: 'Unbox Studio',
    description: 'Clean unboxing studio with overhead camera, clean desk aesthetic, and great lighting. For unboxing creators and product reviewers.',
    category: 'Unboxing Creator Room',
    pricePerHour: 279,
    city: 'Patna',
    area: 'Kankarbagh',
    address: '2nd Floor, Unbox Hub, Kankarbagh, Patna, Bihar 800020',
    images: [
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586953208270-767889db8301?w=800&h=600&fit=crop',
    ],
    equipment: ['Overhead Cam', 'Clean Desk', 'Desk Mic', 'Softbox', 'Phone Stand', 'AC', 'WiFi'],
    features: ['Clean Aesthetic', 'Overhead View', 'Fast Setup', 'Great Lighting'],
    maxPeople: 2,
    rating: 4.5,
    reviewCount: 21,
  },
  {
    name: 'Brand Collab Studio',
    description: 'Spacious collaboration studio designed for brand shoots, influencer collaborations, and team content creation. Multiple zones and professional setup.',
    category: 'Brand Collaboration Room',
    pricePerHour: 699,
    city: 'Patna',
    area: 'Boring Road',
    address: '4th Floor, Collab Space, Boring Road, Patna, Bihar 800001',
    images: [
      'https://images.unsplash.com/photo-1556761175-b4b41ee2b52a?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=600&fit=crop',
    ],
    equipment: ['Multi-zone Setup', 'Professional Camera', 'Lighting Kit', 'Conference Table', 'Props', 'AC', 'WiFi'],
    features: ['Multiple Zones', 'Team Space', 'Brand Ready', 'Production Support'],
    maxPeople: 12,
    rating: 4.8,
    reviewCount: 9,
  },
];

export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const count = await Room.countDocuments();
    
    if (count > 0) {
      return NextResponse.json(
        { success: false, message: 'Database already seeded' },
        { status: 400 }
      );
    }

    const roomsWithSlugs = patnaRooms.map((room) => ({
      ...room,
      slug: room.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '') + `-${Date.now().toString(36)}`,
    }));

    const result = await Room.insertMany(roomsWithSlugs);

    return NextResponse.json(
      { success: true, message: `Seeded ${result.length} creator studios` },
      { status: 200 }
    );
  } catch (error: any) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { success: false, message: error.message },
      { status: 500 }
    );
  }
}
